jobs:
    build:
      docker:
        image: circleci/oraclejdk:1.8
        environment:
          MAJOR_VERSION: 0.9
          MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
          TZ: "/usr/share/zoneinfo/Europe/London"

      branches:
        ignore:
          - gh-pages

      steps:

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              cd ~ && git clone https://github.com/sillelien/build-utils.git && chmod a+x ~/build-utils/*.sh
              [[ ${CIRCLE_BRANCH} != 'master' ]] || ( mvn versions:set -DnewVersion=$(cat .release) && mvn versions:resolve-ranges && mvn versions:lock-snapshots )
               mvn install -e -q -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true -Dmaven.test.skip

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.gnupg
                - ~/.m2
        - run:
            name: test
            command: |
                 mvn -q -T 1C -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true integration-test
            no_output_timeout: 600

        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  git config --global user.email "hello@neilellis.me"
                  git config --global user.name "Neil Ellis"
                  mvn versions:set -DnewVersion=$(cat .release)
                  mvn versions:resolve-ranges
                  mvn versions:lock-snapshots
                  mvn -T 1C -Dmaven.test.skip=true -Drat.skip=true -DskipEnforcer -Dmaven.javadoc.skip=true -DgenerateReports=false package
                  mvn -T 2C -Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser -Dmaven.test.skip=true -Drat.skip=true -DskipEnforcer -Dmaven.javadoc.skip=true -DgenerateReports=false deploy
              fi
